export const SHORTCUTS: { keys: string; label: string }[] = [
  { keys: 'N', label: 'Jump to capture field' },
  { keys: 'Ctrl+K', label: 'Command palette and search' },
  { keys: 'Ctrl+F', label: 'Search everything' },
  { keys: 'Ctrl+1', label: 'Open Queue' },
  { keys: 'Ctrl+2', label: 'Open Today' },
  { keys: 'Ctrl+3', label: 'Open Projects' },
  { keys: 'Ctrl+4', label: 'Open Later' },
  { keys: 'Ctrl+5', label: 'Open Completed' },
  { keys: 'Ctrl+Shift+N', label: 'Create a project' },
  { keys: '↑ / ↓', label: 'Move through items' },
  { keys: 'Space', label: 'Complete or reopen selected' },
  { keys: 'Enter', label: 'Open details for selected' },
  { keys: 'F2', label: 'Rename selected inline' },
  { keys: 'T', label: 'Move selected to Today' },
  { keys: 'Q', label: 'Move selected to Queue' },
  { keys: 'L', label: 'Move selected to Later' },
  { keys: 'Ctrl+D', label: 'Duplicate selected' },
  { keys: 'Delete', label: 'Delete selected' },
  { keys: 'Ctrl+Z', label: 'Undo' },
  { keys: 'Ctrl+Shift+Z', label: 'Redo' },
  { keys: 'Ctrl+,', label: 'Settings' },
  { keys: 'Ctrl+B', label: 'Collapse the sidebar' },
  { keys: 'Esc', label: 'Close panel, menu, or clear selection' }
];
